<?php
/**
 * Dependency manifest for editor.js. Normally generated by @wordpress/scripts;
 * hand-written here because this plugin deliberately ships without a build step.
 */
return array(
	'dependencies' => array(
		'wp-blocks',
		'wp-element',
		'wp-block-editor',
		'wp-components',
		'wp-data',
		'wp-i18n',
	),
	'version'      => '1.0.0',
);
